services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      #target: production
    ports:
      - "3000:3000"
    environment:
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - SECURE_CONNECTITON_TYPE=${SECURE_CONNECTITON_TYPE}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_EMAIL=${MAIL_EMAIL}
      - NEXT_PUBLIC_CLOUDFLARE_SITE_KEY=${NEXT_PUBLIC_CLOUDFLARE_SITE_KEY}
      - CLOUDFLARE_WIDGET_SECRET_KEY=${CLOUDFLARE_WIDGET_SECRET_KEY}
      - NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
      - NEXT_PUBLIC_ENCRYPTION_KEY=${NEXT_PUBLIC_ENCRYPTION_KEY}
      - BACKUP_MASTER_PASSWORD=${BACKUP_MASTER_PASSWORD}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Production modunda volume'leri kaldırın
    # volumes:
    #  - .:/app:ro  # Read-only
    #  - /app/node_modules
    #  - /app/.next
    networks:
      - app-network

networks:
  app-network:
    driver: bridge