// ...existing code...

// Makale etiketleri için sabit liste
export const ARTICLE_TAGS = [
  { value: "javascript", label: "JavaScript" },
  { value: "react", label: "React" },
  { value: "nextjs", label: "Next.js" },
  { value: "nodejs", label: "Node.js" },
  { value: "typescript", label: "TypeScript" },
  { value: "mongodb", label: "MongoDB" },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "fullstack", label: "Full Stack" },
  { value: "webdev", label: "Web Geliştirme" },
  { value: "mobil", label: "Mobil Geliştirme" },
  { value: "devops", label: "DevOps" },
  { value: "ai", label: "Yapay Zeka" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "flutter", label: "Flutter" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "gcp", label: "Google Cloud Platform" },
  { value: "sql", label: "SQL" },
  { value: "nosql", label: "NoSQL" },
  { value: "graphql", label: "GraphQL" },
  { value: "restapi", label: "REST API" },
  { value: "htmlcss", label: "HTML/CSS" },
  { value: "sass", label: "Sass" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "tailwind", label: "Tailwind CSS" },
  { value: "materialui", label: "Material-UI" },
  { value: "redux", label: "Redux" },
  { value: "vue", label: "Vue.js" },
  { value: "angular", label: "Angular" },
  { value: "jquery", label: "jQuery" },
  { value: "git", label: "Git" },
  { value: "github", label: "GitHub" },
  { value: "gitlab", label: "GitLab" },
  { value: "bitbucket", label: "Bitbucket" },
  { value: "ci-cd", label: "CI/CD" },
  { value: "testingtools", label: "Test Araçları" },
  { value: "performance", label: "Performans Optimizasyonu" },
  { value: "accessibility", label: "Erişilebilirlik" },
  { value: "design", label: "Tasarım" },
  { value: "cloud", label: "Bulut Bilişim" },
  { value: "security", label: "Siber Güvenlik" },
  { value: "blockchain", label: "Blockchain" },
  { value: "iot", label: "IoT" },
  { value: "game", label: "Oyun Geliştirme" },
  { value: "arvr", label: "AR/VR" },
  { value: "database", label: "Veritabanı Yönetimi" },
  { value: "algorithms", label: "Algoritmalar ve Veri Yapıları" },
  { value: "networking", label: "Ağ Yönetimi" },
  { value: "testing", label: "Test ve Kalite Güvencesi" },
  { value: "agile", label: "Agile ve Scrum" },
  { value: "uxui", label: "UX/UI Tasarımı" },
  { value: "seo", label: "SEO" },
  { value: "marketing", label: "Dijital Pazarlama" },
  { value: "contentwriting", label: "İçerik Yazımı" },
  { value: "business", label: "İş Geliştirme" },
  { value: "entrepreneurship", label: "Girişimcilik" },
];

// ...existing code...
